import { join } from 'path';

const FILE_STORAGE_PATH = join(__dirname, `../../static`);

const {
  HOST,
  PORT,
  DB_HOST,
  DB_PORT,
  DB_USER,
  DB_PASSWORD,
  DB_NAME,
  JWT_SECRET,
  JWT_EXPIRES,
  FACCEBOOK_CLIENT_ID,
  FACCEBOOK_CLIENT_SECRET,
  AWS_ACCESS_KEY_ID,
  AWS_SECRET_ACCESS_KEY,
  REGION,
  AWS_S3_BUCKET_NAME,
  KEY,
} = process.env;
import { ORM_CONFIG } from './orm.config';

import { APP_CONFIG } from './app.config';

const {
  DEFAULT_STATUS_ID,
} = APP_CONFIG;

export {
  HOST,
  PORT,
  ORM_CONFIG,
  DB_HOST,
  DB_PORT,
  DB_USER,
  DB_PASSWORD,
  DB_NAME,
  JWT_SECRET,
  JWT_EXPIRES,
  FACCEBOOK_CLIENT_ID,
  FACCEBOOK_CLIENT_SECRET,
  AWS_ACCESS_KEY_ID,
  AWS_SECRET_ACCESS_KEY,
  REGION,
  AWS_S3_BUCKET_NAME,
  KEY,
  FILE_STORAGE_PATH,
  DEFAULT_STATUS_ID,
}